project: 
  type: website

website:
  title: "Your_Name Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/your_url
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Your_Name 2023©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "DS250 Projects"
        file: 250_projects.qmd
      - text: "DS350 Projects"
        file: 350_projects.qmd
      - text: "DS450 Projects"
        file: 450_projects.qmd
      - text: "DS460 Projects"
        file: 460_projects.qmd

  sidebar:
    - title: "DS 250 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS250 Projects"
          file: 250_projects.qmd
        - text: "---"
        - text: "Project 0"
          file: 250_Projects/project0.qmd
        - text: "---"
        - text: "Project 1"
          file: 250_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: 250_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: 250_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: 250_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: 250_Projects/project5.qmd
        - text: "---"
        - text: "Project 6"
          file: 250_Projects/project6.qmd
        - text: "---"

    - title: "DS 350 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS350 Projects"
          file: 350_projects.qmd
        - text: "---"
        - text: "Project 0"
          file: 350_Projects/project0.qmd
        - text: "---"
        - text: "Project 1"
          file: 350_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: 350_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: 350_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: 350_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: 350_Projects/project5.qmd
        - text: "---"
        - text: "Project 6"
          file: 350_Projects/project6.qmd
        - text: "---"

    - title: "DS 450 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS450 Projects"
          file: 450_projects.qmd
        - text: "---"
        - text: "Project 0"
          file: 450_Projects/project0.qmd
        - text: "---"
        - text: "Project 1"
          file: 450_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: 450_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: 450_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: 450_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: 450_Projects/project5.qmd
        - text: "---"
        - text: "Project 6"
          file: 450_Projects/project6.qmd
        - text: "---"

    - title: "DS 460 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS450 Projects"
          file: 460_projects.qmd
        - text: "---"
        - text: "Project 0"
          file: 460_Projects/project0.qmd
        - text: "---"
        - text: "Project 1"
          file: 460_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: 460_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: 460_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: 460_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: 460_Projects/project5.qmd
        - text: "---"
        - text: "Project 6"
          file: 460_Projects/project6.qmd
        - text: "---"

        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



